-- system administrator
INSERT INTO "PUBLIC"."USER_ACCOUNTS" (ID, EMAIL, PASSWORD, USERNAME ) VALUES  ( 1, 'adaptserver@gmail.com', 'adapt2010', 'Administrator' )
INSERT INTO "PUBLIC"."USER_ACCOUNTS_PRIVILEGES" (USER_ACCOUNT, PRIVILEGE ) VALUES  ( 1, 'ROLE_ADMINISTRATOR' )
INSERT INTO "PUBLIC"."USER_ACCOUNTS_PRIVILEGES" (USER_ACCOUNT, PRIVILEGE ) VALUES  ( 1, 'ROLE_TEACHER' )
