INSERT INTO "PUBLIC"."USER_ACCOUNTS" (ID, EMAIL, PASSWORD, USERNAME ) VALUES  ( 1, 'john@doe.com', 'doe', 'john' )
INSERT INTO "PUBLIC"."USER_ACCOUNTS" (ID, EMAIL, PASSWORD, USERNAME ) VALUES  ( 2, 'keyser@soze.com', 'soze', 'keyser' )

INSERT INTO "PUBLIC"."USER_ACCOUNTS_PRIVILEGES" (USER_ACCOUNT, PRIVILEGE ) VALUES  ( 2, 'EVALUATOR' )

INSERT INTO "PUBLIC"."SURVEY_TEMPLATES" (ID, TITLE, USER_ID ) VALUES  ( 1, 'zajecia z javy', 2 )

INSERT INTO "PUBLIC"."QUESTION_TEMPLATES" (ID, NUMBER, "TEXT", TEMPLATE, QUESTION_TYPE ) VALUES  ( 1, 1, 'jak oceniasz ''wprowadzenie do jezyka''', 1, 'MULTIPLE_CHOICE' )
INSERT INTO "PUBLIC"."QUESTION_TEMPLATES" (ID, NUMBER, "TEXT", TEMPLATE, QUESTION_TYPE ) VALUES  ( 2, 2, 'jak oceniasz zajecia z ''swing''', 1, 'SINGLE_CHOICE' )
INSERT INTO "PUBLIC"."QUESTION_TEMPLATES" (ID, NUMBER, "TEXT", TEMPLATE, QUESTION_TYPE ) VALUES  ( 3, 3, 'jak oceniasz wyklady z ''podstawy Java''', 1, 'OPEN' )

INSERT INTO "PUBLIC"."ANSWER_TEMPLATES" (ID, NUMBER, "TEXT", QUESTION_ID, REQUIRES_COMMENT, DISALLOWS_OTHER_ANSWERS  ) VALUES  ( 1, 1, 'dobrze', 1, false, false )
INSERT INTO "PUBLIC"."ANSWER_TEMPLATES" (ID, NUMBER, "TEXT", QUESTION_ID, REQUIRES_COMMENT, DISALLOWS_OTHER_ANSWERS  ) VALUES  ( 2, 2, 'przecietnie', 1, false, false )
INSERT INTO "PUBLIC"."ANSWER_TEMPLATES" (ID, NUMBER, "TEXT", QUESTION_ID, REQUIRES_COMMENT, DISALLOWS_OTHER_ANSWERS  ) VALUES  ( 3, 3, 'slabo', 1, true, true )

INSERT INTO "PUBLIC"."ANSWER_TEMPLATES" (ID, NUMBER, "TEXT", QUESTION_ID, REQUIRES_COMMENT, DISALLOWS_OTHER_ANSWERS  ) VALUES  ( 4, 1, 'dobrze', 2, false, true )
INSERT INTO "PUBLIC"."ANSWER_TEMPLATES" (ID, NUMBER, "TEXT", QUESTION_ID, REQUIRES_COMMENT, DISALLOWS_OTHER_ANSWERS  ) VALUES  ( 5, 2, 'przecietnie', 2, false, true )
INSERT INTO "PUBLIC"."ANSWER_TEMPLATES" (ID, NUMBER, "TEXT", QUESTION_ID, REQUIRES_COMMENT, DISALLOWS_OTHER_ANSWERS  ) VALUES  ( 6, 3, 'slabo', 2, true. true )

INSERT INTO "PUBLIC"."STUDENT_GROUPS" (ID, GROUP_NAME) VALUES (1,'TEST GROUP')
INSERT INTO "PUBLIC"."STUDENT_GROUPS_MEMBERS" (GROUP_ID,GROUP_ROLE,MEMBER_ID) VALUES (1,'STUDENT',1)
INSERT INTO "PUBLIC"."STUDENT_GROUPS_TEMPLATES" (GROUP_ID, TEMPLATE_ID) VALUES (1,1)